default:
  image: ubuntu:14.04
  before_script:
    - apt-get update && apt-get install -y python2.7 python-pip tar bash bash-doc bash-completion wget zip clang-format-3.8
  
job:
  script:
    - mkdir /protoc
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip -P /protoc
    - unzip /protoc/protoc-3.14.0-linux-x86_64.zip -d /protoc
    - export PATH=/protoc/bin:$PATH
    # Build all test...
    - chmod +x ./compile_base.py
    # Generates new Rcp.proto from raw and all test...
    - ./compile_base.py -g -r -1
    - ./compile_base.py -l cpp -1 -k
    #    - ./compile_base.py -l csharp -1 -k
    #    - ./compile_base.py -l java -1 -k
    #    - ./compile_base.py -l js -1 -k
    #    - ./compile_base.py -l python -1 -k
    #    - ./compile_base.py -l php -1 -k
    #    - ./compile_base.py -l objc -1 -k
    #    - ./compile_base.py -l ruby -1 -k
    - chmod +x ./compile_src.py
    - ./compile_src.py cpp --include_imports --include_source_info --generate_desc
    #    - ./compile_src.py csharp --include_imports --include_source_info --generate_desc
    #    - ./compile_src.py java --java_multiple_files --include_imports --include_source_info --generate_desc
    #    - ./compile_src.py js
    #    - ./compile_src.py python
    #    - ./compile_src.py php --include_imports --include_source_info --generate_desc
    #    - ./compile_src.py objc --include_imports --include_source_info --generate_desc
    #    - ./compile_src.py ruby
    - clang-format-3.8 -i -style file $(find src -name "*.proto")
    # - git diff --exit-code
