language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "3.8"
install:
  - pushd /tmp
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
  - unzip protoc-3.14.0-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  # Build all test...
  - chmod +x ./compile_base.py
  # Generates new Rcp.proto from raw and all test...
  - ./compile_base.py -g -r
  - ./compile_base.py -l cpp -k
  #  - ./compile_base.py -l csharp -k
  #  - ./compile_base.py -l java -k
  #  - ./compile_base.py -l js -k
  #  - ./compile_base.py -l python -k
  #  - ./compile_base.py -l php -k
  #  - ./compile_base.py -l objc -k
  #  - ./compile_base.py -l ruby -k
  #  - ./compile_base.py -l swif -k
  - chmod +x ./compile_src.py
  - ./compile_src.py cpp
  #  - ./compile_src.py csharp
  #  - ./compile_src.py java --java_multiple_files
  #  - ./compile_src.py js
  #  - ./compile_src.py python
  #  - ./compile_src.py php
  #  - ./compile_src.py objc
  #  - ./compile_src.py ruby
  - clang-format-3.8 -i -style file $(find src -name "*.proto")
  # - git diff --exit-code
